[theme]
theme = "modern"
#[theme.overrides]
#separator = ""

[icons]
icons = "awesome6"
[icons.overrides]
cogs = " "
backlight_empty = "  "
backlight_partial1 = "  "
backlight_partial2 = "  "
backlight_partial3 = "  "
backlight_full = "  "
pomodoro = "  "
volume_full = "  "
volume_half = "  "
volume_empty = "  "
volume_muted = "  "
mail = "  "
time = "  "

[[block]]
block = "load"
format = "$icon $1m.eng(w:3) $5m.eng(w:3) "

# i3status-rust currently does not process database updates correctly.
# # currently yay is not compilable with pacman-git. So we are stuck without the
# # AUR update counter for now
[[block]]
block = "pacman"
interval = 300
format = "$icon $pacman+$aur "
format_up_to_date = "0"
critical_updates_regex = "(linux|linux-lts|linux-zen|linux-amd|linux-ck|firefox|sudo|librewolf|linux-amd|curl|doas|systemd)"
aur_command = "yay -Qua"
[[block.click]]
button = "right"
update = true

[[block]]
block = "net"

[[block]]
block = "notify"
driver = "swaync"
format = "$icon {$notification_count |}"
[[block.click]]
button = "left"
action = "show"
[[block.click]]
button = "right"
action = "toggle_paused"

[[block]]
block = "memory"
format = "$icon $mem_used.eng(w:3)/$mem_total.eng(w:3) ($mem_avail_percents) "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"
driver = "pulseaudio"

[[block]]
block = "battery"
driver = "upower"

[[block]]
block = "time"
format = "$icon $timestamp.datetime(f:'%d.%m.%Y %H:%M:%S ')"
interval = 1

